"use strict";

var dayEvent = new Array();

dayEvent[1] = "";
dayEvent[2] = "<br>Business Meeting";
dayEvent[3] = "";
dayEvent[4] = "";
dayEvent[5] = "";
dayEvent[6] = "<br>Production";
dayEvent[7] = "";
dayEvent[8] = "";
dayEvent[9] = "";
dayEvent[10] = "";
dayEvent[11] = "";
dayEvent[12] = "";
dayEvent[13] = "";
dayEvent[14] = "";
dayEvent[15] = "";
dayEvent[16] = "";
dayEvent[17] = "";
dayEvent[18] = "<br>Movies";
dayEvent[19] = "";
dayEvent[20] = "";
dayEvent[21] = "";
dayEvent[22] = "";
dayEvent[23] = "";
dayEvent[24] = "";
dayEvent[25] = "<br>Someone's birthday party";
dayEvent[26] = "";
dayEvent[27] = "";
dayEvent[28] = "";
dayEvent[29] = "";
dayEvent[30] = "<br>Planning/Meeting";
